sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - rpm
install:
- git clone --branch 2.4 --depth=1 --no-single-branch https://github.com/Graylog2/graylog2-server ../graylog2-server
- (cd ../graylog2-server && mvn -DskipTests=true compile -B -V)
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -B -V
script:
- mvn package -B